name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "SnowGirl"
          replace: "AnkiVector"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Welcome to Amanda'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: TR-TECH-GUIDE
          commit_user_email: tharukrenujatechguide@gmail.com
          commit_author: TR-TECH-GUIDE <tharukrenujatechguide@gmail.com>
